---
- hosts: "{{ host | default('physical') }}"
  tasks:
    - name: Check contrail status
      command: contrail-status
      register: output
    - debug: 
        var: output.stdout_lines

    - debug:
        msg: I do nodemgr initializing and schema backup
      when: '"nodemgr: initializing" in output.stdout_lines | join and "schema: backup" in output.stdout_lines | join'      
