- hosts: m14-controllers
  tasks:
    - name: make config absent
      lineinfile:
        dest: "{{ item.dest }}"
        state: absent
        regexp: "{{ item.regexp }}"
      with_items:
        - {dest: '/etc/kolla/heat-engine/heat.conf', regexp: 'max_json_body_size=8388608'}
        - {dest: '/etc/kolla/heat-engine/heat.conf', regexp: 'max_template_size=8388608'}
        - {dest: '/etc/kolla/heat-engine/heat.conf', regexp: 'max_request_body_size=8388608'}
        - {dest: '/etc/kolla/heat-engine/heat.conf', regexp: 'max_resources_per_stack=50000'}
        - {dest: '/etc/kolla/heat-api-cfn/heat.conf', regexp: 'max_json_body_size=8388608'}
        - {dest: '/etc/kolla/heat-api-cfn/heat.conf', regexp: 'max_template_size=8388608'}
        - {dest: '/etc/kolla/heat-api-cfn/heat.conf', regexp: 'max_request_body_size=8388608'}
        - {dest: '/etc/kolla/heat-api-cfn/heat.conf', regexp: 'max_resources_per_stack=50000'}
        - {dest: '/etc/kolla/heat-api/heat.conf', regexp: 'max_json_body_size=8388608'}
        - {dest: '/etc/kolla/heat-api/heat.conf', regexp: 'max_template_size=8388608'}
        - {dest: '/etc/kolla/heat-api/heat.conf', regexp: 'max_request_body_size=8388608'}
        - {dest: '/etc/kolla/heat-api/heat.conf', regexp: 'max_resources_per_stack=50000'}