---
- hosts: virtual-master
  tasks:
    - name: Uninstall ansible 
      command: pip uninstall -y ansible

    - name: Install ansible 2.5.2
      command: pip install ansible==2.5.2
  
- hosts: virtual-rem
  tasks:
    - name: Uninstall ansible 
      command: yum remove -y ansible  # pip uninstall -y ansible
