---
- hosts: server-manager
  tasks:
    - name: Reimage servers
      command: server-manager reimage --no_confirm --server_id "{{ item.split('.')[0] }}" centos-7.6
      loop: "{{ groups['bare-metal'] }}"
      register: output
    
    - debug:
        var: output
     
  
