---
- hosts: server-manager
  vars_prompt:
    - name: "server"
      prompt: "Enter the name of the server to reimage"
  tasks:
    - name: Reimage servers
      command: server-manager reimage --no_confirm --server_id {{server}} centos-7.6
    - debug: 
        var: server

  
